config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'

  resources :pages do
    collection do
      post 'send_request', to: "pages#send_request"
    end
  end

  get '/google7e35f88d3d0c8196.html',
  to: proc { |env| [200, {}, ["google-site-verification: google7e35f88d3d0c8196.html"]] }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def send_request
    RequestMailer.new_request(params).deliver_now
    flash[:notice] = "Votre demande de rêve a bien été envoyée, je vous recontacte trés vite"
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <div class="container">
      <div class="row">
          <div class="col-md-4">
              <ul class="list-inline quicklinks">
                  <li><a href="#">&copy; OnceAway</a>
                  </li>
              </ul>
          </div>
          <div class="col-md-4">
              <ul class="list-inline social-buttons">
                  <li><a href="#"><i class="fa fa-instagram"></i></a>
                  </li>
                  <li><a href="#"><i class="fa mail fa-envelope-o"></i></a>
                  </li>
              </ul>
          </div>
          <div class="col-md-4">
              <ul class="list-inline">
                  <li><i class="fa fa-phone-square"></i></li>
                  <li>+ 33 6 18 49 20 31</li>
              </ul>
              <ul class="list-inline">
                  <li><i class="fa fa-envelope"></i></li>
                  <li>marie@onceaway.com</li>
              </ul>
          </div>
      </div>
  </div>
</footer>

app/views/layouts/_nav.html.erb
<!-- Navigation -->
<nav class="navbar navbar-default active navbar-fixed-top">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header page-scroll">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand page-scroll visible-xs" href="#page-top">
              <%= image_tag("logo.png", size: "30")%>
            </a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
                <li class="hidden">
                    <a href="#page-top"></a>
                </li>
                <li>
                    <a class="page-scroll" href="#concept">Concept</a>
                </li>
                <li>
                    <a class="page-scroll" href="#destinations">Destinations</a>
                </li>
                <li>
                    <a class="page-scroll" href="#about">Marie</a>
                </li>
                <li>
                    <a class="page-scroll" href="#contact">Contactez Moi</a>
                </li>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

  <meta charset="utf-8">
  <title>Onceaway, créateur de voyages de rêves</title>
  <meta name="description" content="Specialiste du voyage sur mesure en Afrique, Amerique Latine, Caraïbes, Océanie et Asie, Once Away personnalise votre voyage selon vos envies, de insolite, de l'extraordinaire, du différent jusqu'à l'extreme luxe.">
  <meta name="author" content="Marie Mulliez">

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <link href='https://fonts.googleapis.com/css?family=Poiret+One' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Dosis' rel='stylesheet' type='text/css'>
</head>
<body id="page-top" class="index">

<%= render 'layouts/nav' %>
<%= render 'layouts/flashes' %>

<%= yield %>

<%= render 'layouts/footer' %>

</body>
</html>

app/views/pages/home.html.erb
<!-- logo -->
<div>
  <a class="logo-brand page-scroll hidden-xs" href="#page-top">
    <%= image_tag("logo.png", size: "50")%>
  </a>
</div>
<!-- social logo -->
<div class="social-logo hidden-xs">
  <a href="https://www.linkedin.com/in/marie-mulliez-a177159?authType=NAME_SEARCH&authToken=UCIT&locale=en_US&trk=tyah&trkInfo=clickedVertical%3Amynetwork%2CclickedEntityId%3A28646515%2CauthType%3ANAME_SEARCH%2Cidx%3A1-1-1%2CtarId%3A1463395580363%2Ctas%3Amarie%20mulliez" target="_blank"><i class="fa linkedin fa-linkedin"></i></a>
  <a href="#contact"><i class="fa mail fa-envelope-o"></i></a>
</div>

<!-- Header -->
<header>
    <div class="container">
        <div class="intro-text">
<!--             <h1 class="intro-heading">ONCE AWAY</h1> -->
            <h2 class="intro-lead-in">Créateur de voyages de rêves</h2>
<!-- <a href="#destinations" class="page-scroll btn btn-xl">Voir les destinations</a> -->
            <a href="#concept" class="btn btn-circle page-scroll text-center">
                <i class="fa fa-angle-double-down"></i>
            </a>
            <a href="http://www.frankmulliez.com/fr/" target="_blank" id="copy-frank">&copy; Frank Mulliez</a>
        </div>
    </div>
</header>

<section id="concept">
  <div class="container">
    <div class="row">
      <div class="col-lg-12 text-center">
          <h2 class="section-heading">Le concept</h2>
          <h3 class="section-subheading text-muted">Comment ça marche</h3>
      </div>
    </div>
    <div class="row">
      <div class="col-md-3">
        <div class="circle">
          <h4>Facile</h4>
        </div>
        <div class="added-value">
          <p>Un seul contact : je suis votre interlocutrice unique avant pendant et après votre voyage.</p>
        </div>
      </div>
      <div class="col-md-3">
        <div class="circle">
          <h4 class="sur-mesure">Sur Mesure</h4>
        </div>
        <div class="added-value">
          <p>Je vous aide à construire le voyage de vos rêves. Je m’adapte à chacune de vos envies.</p>
        </div>
      </div>
      <div class="col-md-3">
        <div class="circle">
          <h4>Malin</h4>
        </div>
        <div class="added-value">
          <p>Je vous partage mes pépites. Vous savez, ces bons plans locaux qui rendent chaque moment extraordinaire !</p>
        </div>
      </div>
      <div class="col-md-3">
        <div class="circle">
          <h4>Rassurant</h4>
        </div>
        <div class="added-value">
          <p>Je propose uniquement les destinations que je connais. Je m’occupe de tout, un véritable gain de temps !</p>
        </div>
      </div>
    </div>
  </div>
</section>


<!-- Destinations Section -->
<section id="destinations" class="bg-light-grey">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12 text-center">
                <h2 class="section-heading">Destinations</h2>
                <h3 class="section-subheading text-muted">Quel lieu insolite rêvez vous de découvrir ?</h3>
            </div>
        </div>
        <div class="row text-center">
            <div class="col-md-2 col-md-offset-1">
                <h4 class="destination-heading">Afrique</h4>
                <ul class="text-muted destination-list">
                  <li>Afrique du Sud</li>
                  <li>Botswana</li>
                  <li>Kenya</li>
                  <li>Madagascar</li>
                  <li>Malawi</li>
                  <li>Mozambique</li>
                  <li>Namibie</li>
                  <li>Tanzanie</li>
                  <li>Zambie</li>
                  <li>Zimbabwe</li>
                </ul>
            </div>
            <div class="col-md-2">
                <h4 class="destination-heading">Amerique Latine</h4>
                <ul class="text-muted destination-list">
                  <li>Argentine</li>
                  <li>Bresil</li>
                  <li>Bolivie</li>
                  <li>Chili</li>
                  <li>Equateur</li>
                  <li>Perou</li>
                  <li>Uruguay</li>
                </ul>
            </div>
            <div class="col-md-2">
                <h4 class="destination-heading">Caraïbes</h4>
                <ul class="text-muted destination-list">
                  <li>Cuba</li>
                  <li>Costa Rica</li>
                  <li>Martinique</li>
                  <li>Mexique</li>
                  <li>Nicaragua</li>
                  <li>Panama</li>
                </ul>
            </div>
            <div class="col-md-2">
                <h4 class="destination-heading">Océanie</h4>
                <ul class="text-muted destination-list">
                  <li>Australie</li>
                  <li>Nouvelle Zelande</li>
                  <li>Polynesie</li>
                </ul>
            </div>
            <div class="col-md-2">
                <h4 class="destination-heading">Asie</h4>
                <ul class="text-muted destination-list">
                  <li>Birmanie</li>
                  <li>Cambodge</li>
                  <li>Inde</li>
                  <li>Indonesie</li>
                  <li>Japon</li>
                  <li>Laos</li>
                  <li>Thailande</li>
                  <li>Vietnam</li>
                </ul>
            </div>
        </div>
    </div>
</section>

<!-- Inspiration Section -->
<!-- <section id="inspiration" class="bg-light-grey">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12 text-center">
                <h2 class="section-heading">Inspiration</h2>
                <h3 class="section-subheading text-muted">Mes anecdotes de voyages</h3>
            </div>
        </div> -->
        <!-- Inspiration 1 -->
<!--         <div class="row">
          <div class="col-md-6 inspiration-item inspiration-one"></div>
          <div class="col-md-6 inspiration-comment">
            <h4>Emotion/sentiment</h4>
            <p class="text-muted">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt ut voluptatum eius sapiente, totam reiciendis temporibus qui quibusdam, recusandae sit vero unde, sed, incidunt et ea quo dolore laudantium consectetur!</p>
          </div>
        </div> -->
        <!-- Inspiration 2 -->
<!--         <div class="row">
          <div class="col-md-6 inspiration-item inspiration-two visible-sm visible-xs"></div>
          <div class="col-md-6 inspiration-comment">
            <h4>Emotion/sentiment</h4>
            <p class="text-muted">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt ut voluptatum eius sapiente, totam reiciendis temporibus qui quibusdam, recusandae sit vero unde, sed, incidunt et ea quo dolore laudantium consectetur!</p>
          </div>
          <div class="col-md-6 inspiration-item inspiration-two hidden-sm hidden-xs"></div>
        </div> -->
        <!-- Inspiration 3 -->
<!--         <div class="row">
          <div class="col-md-6 inspiration-item inspiration-three"></div>
          <div class="col-md-6 inspiration-comment">
            <h4>Emotion/sentiment</h4>
            <p class="text-muted">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt ut voluptatum eius sapiente, totam reiciendis temporibus qui quibusdam, recusandae sit vero unde, sed, incidunt et ea quo dolore laudantium consectetur!</p>
          </div>
        </div> -->
        <!-- Inspiration 4 -->
<!--         <div class="row">
          <div class="col-md-6 inspiration-item inspiration-four visible-sm visible-xs"></div>
          <div class="col-md-6 inspiration-comment">
            <h4>Emotion/sentiment</h4>
            <p class="text-muted">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt ut voluptatum eius sapiente, totam reiciendis temporibus qui quibusdam, recusandae sit vero unde, sed, incidunt et ea quo dolore laudantium consectetur!</p>
          </div>
          <div class="col-md-6 inspiration-item inspiration-four hidden-sm hidden-xs"></div>
        </div>
    </div>
</section> -->

<!-- About Section -->
<section id="about">
    <div class="container">
      <div class="row">
          <div class="col-lg-12 text-center">
              <h2 class="section-heading">Marie</h2>
              <h3 class="section-subheading text-muted">Créatrice de voyages</h3>
          </div>
      </div>
      <div class="row">
        <div class="col-sm-8 col-sm-offset-2 col-lg-4 col-lg-offset-4">
          <div class="about-image">
            <%= image_tag("marie.jpg", class: "avatar-bordered img-responsive", alt: "Marie Mulliez") %>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-8 col-md-offset-2 text-center">
          <div class="about-panel">
            <div class="about-heading">
              <h4 class="subheading">Mon expérience</h4>
            </div>
            <div class="about-body">
              <p class="text-muted">Amoureuse de l’Afrique et de l’Amérique latine, j’ai sillonné les 5 continents et je partage ma vie entre la France, l’Espagne et l’Argentine. <br>
              <br>
              Quand je voyage, j’aime apprendre quelques mots dans la langue du pays, me promener au hasard des ruelles, gouter aux spécialités, ou encore m’asseoir dans le petit café préféré des habitants du quartier. Ce sont de bons moyens de rencontrer des locaux, de découvrir la culture du pays et de vivre des moments inoubliables. <br>
              <br>
              J’aurai plaisir à vous guider et partager mes expériences, et même à vous surprendre en vous faisant découvrir ce que peut-être vous ne soupçonnez pas.
            </div>
          </div>
        </div>
      </div>
    </div>
</section>

<!-- Comment Section -->
<section id="avis" class="bg-light-grey">
    <div class="container">
      <div class="row">
          <div class="col-lg-12 text-center">
              <h2 class="section-heading">Les avis</h2>
              <h3 class="section-subheading text-muted">Quelques avis de voyageurs</h3>
          </div>
      </div>

      <div class="row">
        <div class="col-md-6 col-md-offset-2">
          <div class="testimonials">
            <p class="quote text-muted">"C'est un régal des yeux, humain et odeurs... Depaysement total, découverte avec un regard ébahi"</p>
            <h4 class="author">Christian et Marie-Christine à Cuba</h4>
          </div>
        </div>
      </div>

<!--       <div class="row">
        <div class="col-md-6 col-md-offset-4">
          <div class="testimonials">
            <p class="quote text-muted">"Denim you probably haven't heard of. Lorem ipsum dolor met consectetur adipisicing sit amet, consectetur adipisicing elit, of them jean shorts sed magna aliqua. Lorem ipsum dolor met."</p>
            <h4 class="author">Auteur</h4>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col-md-6 col-md-offset-2">
          <div class="testimonials">
            <p class="quote text-muted">"Denim you probably haven't heard of. Lorem ipsum dolor met consectetur adipisicing sit amet, consectetur adipisicing elit, of them jean shorts sed magna aliqua. Lorem ipsum dolor met."</p>
            <h4 class="author">Auteur</h4>
          </div>
        </div>
      </div> -->
    </div>
</section>

<!-- Contact Section -->
<section id="contact">
    <div class="container">
      <div class="row">
          <div class="col-lg-12 text-center">
              <h2 class="section-heading">Contactez moi</h2>
              <h3 class="section-subheading text-muted">Votre premier pas vers le voyage</h3>
          </div>
      </div>
      <div class="row">
        <%= simple_form_for :new_request, url: send_request_pages_path, method: :post do |form| %>
          <div class="col-md-6">
            <%= form.input :name, label: false, placeholder: "Nom" %>
            <%= form.input :email, label: false, placeholder: "Email" %>
          </div>
          <div class="col-md-6">
            <%= form.input :phone_number, label: false, placeholder: "Télephone" %>
            <%= form.input :location, label: false, placeholder: "Lieu du voyage" %>
          </div>
          <div class="col-md-12">
          <%= form.input :description, as: :text, label: false, placeholder: 'Quel voyage desirez vous ?'%>
          </div>
          <div class="col-md-12 text-center">
          <%= form.submit 'Envoyer', class: 'btn btn-xl' %>
          </div>
        <% end %>
      </div>
    </div>
</section>